apiVersion: v1
kind: BuildConfig
metadata:
  name: doosan-poc-fuse
  labels:
    app: doosan-poc-fuse
    group: com.redhat
    provider: fabric8
    version: '1.0'
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'doosan-poc-fuse:latest'
  source:
    type: Git
    git:
      uri: "http://gogs.51.15.56.81.nip.io/gogs/doosan-poc-fuse.git"
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'jboss-fuse70-java-openshift:1.0'
        namespace: openshift
    type: Source
  triggers:
    - type: GitHub
      github:
        secret: h_YU4ZQEAFL2J-kus6DD
    - type: Generic
      generic:
        secret: sGW6f3VLdVOfMJyv-8C_
